try{
    let a=5;

let sum=a+b;
console.log(sum);

}
catch(error){
    console.error(error.message);
    
}
finally{
    console.log("hi");   
}

